(()=>{'use strict';
const $=id=>document.getElementById(id),s=WLState.data;WLMatches.ensure();
function saveRender(){WLState.save();WLUI.render();const b=$('betslipBalance');if(b)b.textContent=Math.floor(s.tokens).toLocaleString('ru-RU');}
window.WLRhythm?.init();
$('boostButton').onclick=()=>{if(!WLClicker.buyBoost())return WLUI.toast('Нужно 500 энергии');saveRender();};
$('rebirthButton').onclick=()=>{const gain=WLPrestige.reward();if(!gain)return WLUI.toast('Цель перерождения ещё не достигнута');if(!confirm(`Переродиться и получить ${gain} очк. славы? Прогресс кликера будет сброшен.`))return;const result=WLPrestige.rebirth();$('prestigeMessage').textContent=result.message;WLUI.toast(result.message);saveRender();};
$('dailyButton').onclick=()=>{if(!WLClicker.claimDaily())return WLUI.toast('Уже получено');WLUI.toast('+энергия и +200 жетонов');saveRender();};
document.addEventListener('click',e=>{const b=e.target.closest('[data-buy],[data-talent],[data-q],[data-mid],[data-remove]');if(!b)return;if(b.dataset.talent){const result=WLPrestige.buyTalent(b.dataset.talent);if(!result.ok)return WLUI.toast(result.message);WLUI.toast(result.message);saveRender();}else if(b.dataset.buy){const result=WLShop.buy(b.dataset.buy);if(!result.ok)return WLUI.toast(result.message);saveRender();}else if(b.dataset.q){s.claimed[b.dataset.q]=true;s.energy+=Number(b.dataset.r);saveRender();}else if(b.dataset.remove){WLCoupon.remove(b.dataset.remove);WLUI.render();}else if(b.dataset.mid){const type=document.querySelector('input[name="ticketType"]:checked').value;WLCoupon.select(b.dataset.mid,b.dataset.key,type);WLUI.render();}});
$('newRoundButton').onclick=()=>{WLSimulator.tick();WLUI.render();WLUI.toast('Завершённые матчи обновятся автоматически');};
$('stakeInput').oninput=WLUI.payout;document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{$('stakeInput').value=b.dataset.quick==='max'?Math.floor(s.tokens):b.dataset.quick;WLUI.payout();});
document.querySelectorAll('input[name="ticketType"]').forEach(r=>r.onchange=()=>{WLCoupon.clear();WLUI.render();});
$('feedMatch').onchange=e=>{s.feedMatchId=e.target.value;if(window.WLVisualizer)WLVisualizer.select(s.feedMatchId);WLUI.render();};
$('placePredictionButton').onclick=()=>{const btn=$('placePredictionButton');if(btn.dataset.submitting==='1')return;btn.dataset.submitting='1';btn.disabled=true;const type=document.querySelector('input[name="ticketType"]:checked').value,result=WLCoupon.place(type,$('stakeInput').value);$('couponMessage').textContent=result.message;if(result.ok){$('stakeInput').value='';WLUI.toast('✓ Ставка принята');saveRender();}else WLUI.payout();setTimeout(()=>{btn.dataset.submitting='0';WLUI.payout();},350);};
function promo(){const result=WLPromo.redeem($('promoInput').value);$('promoResult').textContent=result.message;if(result.ok)saveRender();}
$('promoButton').onclick=promo;$('promoInput').onkeydown=e=>{if(e.key==='Enter')promo();};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>WLNavigation.go(b.dataset.screen));
$('exportButton').onclick=WLProfile.exportSave;$('importButton').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;WLProfile.importSave(f,ok=>{if(ok){WLUI.toast('Импортировано');saveRender();}else WLUI.toast('Ошибка файла');});};
$('resetButton').onclick=()=>{if(confirm('Сбросить прогресс?')){localStorage.removeItem(WLState.KEY);location.reload();}};
const elapsed=Math.min(28800,Math.max(0,(Date.now()-s.lastSave)/1000));if(elapsed>10&&s.passive){const off=Math.floor(elapsed*(WLEconomy.passiveValue?WLEconomy.passiveValue():s.passive));s.energy+=off;s.totalEnergy+=off;s.totalEnergyRun=(s.totalEnergyRun||0)+off;setTimeout(()=>WLUI.toast(`Офлайн-доход +${off}`),400);}
WLUI.render();const initialBalance=$('betslipBalance');if(initialBalance)initialBalance.textContent=Math.floor(s.tokens).toLocaleString('ru-RU');WLState.save();setInterval(()=>{WLClicker.tick();WLSimulator.tick();WLUI.render();},1000);setInterval(()=>WLState.save(),5000);window.addEventListener('beforeunload',()=>WLState.save());
})();
