(()=>{'use strict';
const teams=[['Real Madrid',88,82],['Liverpool',87,79],['Barcelona',85,80],['Inter',82,84],['Bayern',89,78],['Arsenal',84,81],['PSG',88,76],['Milan',80,80],['Juventus',79,83],['Dortmund',83,75],['Chelsea',78,82],['Napoli',82,77]];
const MATCH_DURATION=300000;
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
function rng(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function overlaps(startA,endA,startB,endB){return startA<endB&&startB<endA;}
function busyTeamNames(matches,startAt,endAt){const busy=new Set();(matches||[]).forEach(m=>{if(!m||m.status==='FINISHED')return;const ms=Number(m.start),me=Number(m.end);if(Number.isFinite(ms)&&Number.isFinite(me)&&overlaps(startAt,endAt,ms,me)){busy.add(m.home);busy.add(m.away);}});return busy;}
function pairForSlot(matches,startAt){const endAt=startAt+MATCH_DURATION,busy=busyTeamNames(matches,startAt,endAt),available=teams.filter(t=>!busy.has(t[0]));const pool=available.length>=2?available:teams.filter(t=>!busy.has(t[0]));if(pool.length<2)return null;const a=pool[Math.floor(Math.random()*pool.length)];let b;do b=pool[Math.floor(Math.random()*pool.length)];while(b[0]===a[0]);return[a,b];}
const oddFromProbability=p=>clamp(Math.round((.93/Math.max(.025,p))*100)/100,1.05,18);
function playerRating(teamName,role,index,attack,defense){const r=rng(hash(`${teamName}|${role}|${index}|rating`));const roleBase=role==='GK'?defense:role==='DF'?defense*.94+attack*.06:role==='MF'?(attack+defense)/2:attack;return Math.round(clamp(roleBase-4+r()*8,68,94));}
function teamFacts(teamName,attack,defense,seedTag){const r=rng(hash(`${teamName}|${seedTag}|facts-v2`));const lineup=window.WLTeamDB?.lineup?.(teamName)||[];const ratings=lineup.length?lineup.map((p,i)=>playerRating(teamName,p.role,i+1,attack,defense)):Array.from({length:11},(_,i)=>Math.round((attack+defense)/2-3+r()*6));const lineupRating=Math.round(ratings.reduce((a,b)=>a+b,0)/ratings.length);let wins=0,draws=0,losses=0,gf=0,ga=0;const form=[];for(let i=0;i<5;i++){const strength=(attack+defense+lineupRating)/3;const roll=r()+clamp((strength-81)/45,-.12,.15);let res;if(roll>.63){res='W';wins++;gf+=2+Math.floor(r()*2);ga+=Math.floor(r()*2);}else if(roll>.34){res='D';draws++;const g=Math.floor(r()*3);gf+=g;ga+=g;}else{res='L';losses++;gf+=Math.floor(r()*2);ga+=1+Math.floor(r()*3);}form.push(res);}const topPlayers=lineup.map((p,i)=>({name:p.shortName||p.fullName,role:p.role,rating:ratings[i]})).sort((a,b)=>b.rating-a.rating).slice(0,3);return{lineupRating,attack,defense,wins,draws,losses,gf,ga,form,topPlayers,fitness:Math.round(82+r()*16),chemistry:Math.round(76+r()*22)};}
function factualModel(home,away,seedTag){const hf=teamFacts(home[0],home[1],home[2],seedTag),af=teamFacts(away[0],away[1],away[2],seedTag);const homePower=hf.lineupRating*.34+hf.attack*.30+hf.defense*.20+hf.wins*1.8+hf.chemistry*.08+hf.fitness*.05+4.5;const awayPower=af.lineupRating*.34+af.attack*.30+af.defense*.20+af.wins*1.8+af.chemistry*.08+af.fitness*.05;const diff=(homePower-awayPower)/28;let draw=clamp(.27-Math.abs(diff)*.035,.18,.30),p1=(1-draw)/(1+Math.exp(-diff)),p2=1-draw-p1;const sum=p1+draw+p2;return{facts:{home:hf,away:af},probabilities:{P1:p1/sum,X:draw/sum,P2:p2/sum}};}
function createMatch(i=0,startAt=Date.now(),existingMatches=[]){let selected=pairForSlot(existingMatches,startAt);if(!selected){startAt=Math.max(startAt,...(existingMatches||[]).filter(m=>m&&m.status!=='FINISHED').map(m=>Number(m.end)||startAt))+30000;selected=pairForSlot(existingMatches,startAt);}const[h,a]=selected,now=Date.now(),model=factualModel(h,a,`${startAt}|${i}`),live=startAt<=now;const announcedAt=now,openDelay=8000+Math.random()*12000,marketOpenAt=live?now:Math.min(startAt-12000,announcedAt+openDelay);return{id:'m'+startAt+'_'+i+'_'+Math.random().toString(36).slice(2,6),home:h[0],away:a[0],homeAttack:h[1],homeDefense:h[2],awayAttack:a[1],awayDefense:a[2],start:startAt,end:startAt+MATCH_DURATION,announcedAt,marketOpenAt,marketOpenedAt:live?now:0,scoreH:0,scoreA:0,status:live?'LIVE':'UPCOMING',events:live?["0' Матч начался"]:[`Матч анонсирован. Линия формируется рынком.`],odds:live?Object.fromEntries(Object.entries(model.probabilities).map(([k,p])=>[k,oddFromProbability(p)])):{P1:0,X:0,P2:0},oddsTarget:{P1:0,X:0,P2:0},oddsTrend:{P1:0,X:0,P2:0},fairProbabilities:model.probabilities,preMatchFacts:model.facts,marketBets:{P1:0,X:0,P2:0},marketActivityUntil:0,nextMarketPulse:now+1000,result:null,lastEvent:live?startAt:0};}
function createInitialSchedule(){const now=Date.now(),starts=[now-15000,now+75000,now+195000];starts.push(Math.random()<.45?now+225000:now+330000);const matches=[];starts.forEach((start,i)=>matches.push(createMatch(i,start,matches)));return matches;}
function nextScheduledStart(matches){const now=Date.now(),active=matches.filter(m=>m.status!=='FINISHED'),latestStart=Math.max(now,...active.map(m=>Number(m.start)||now)),latestEnd=Math.max(now,...active.map(m=>Number(m.end)||now));return Math.random()<.32?Math.max(now+30000,latestEnd-(45000+Math.random()*90000)):Math.max(now+45000,latestStart+75000+Math.random()*105000);}
function hasTeamConflicts(matches){for(let i=0;i<matches.length;i++)for(let j=i+1;j<matches.length;j++){const a=matches[i],b=matches[j];if(!a||!b||a.status==='FINISHED'||b.status==='FINISHED')continue;if(overlaps(Number(a.start),Number(a.end),Number(b.start),Number(b.end))&&(a.home===b.home||a.home===b.away||a.away===b.home||a.away===b.away))return true;}return false;}
function isValidMatch(m){return !!(m&&typeof m.id==='string'&&typeof m.home==='string'&&typeof m.away==='string'&&Number.isFinite(Number(m.start))&&Number.isFinite(Number(m.end))&&m.odds&&['P1','X','P2'].every(k=>Number.isFinite(Number(m.odds[k])))&&Array.isArray(m.events));}
function normalizeMatch(m){m.homeAttack=Number(m.homeAttack)||80;m.homeDefense=Number(m.homeDefense)||80;m.awayAttack=Number(m.awayAttack)||80;m.awayDefense=Number(m.awayDefense)||80;m.scoreH=Number(m.scoreH)||0;m.scoreA=Number(m.scoreA)||0;m.status=m.status==='FINISHED'?'FINISHED':Date.now()<Number(m.start)?'UPCOMING':'LIVE';m.announcedAt=Number(m.announcedAt)||Date.now();m.marketOpenAt=Number(m.marketOpenAt)||Math.min(Number(m.start)-12000,m.announcedAt+10000);m.marketOpenedAt=Number(m.marketOpenedAt)||0;m.oddsTarget=Object.assign({P1:0,X:0,P2:0},m.oddsTarget||{});m.oddsTrend=Object.assign({P1:0,X:0,P2:0},m.oddsTrend||{});m.marketBets=Object.assign({P1:0,X:0,P2:0},m.marketBets||{});m.marketActivityUntil=Number(m.marketActivityUntil)||0;m.nextMarketPulse=Number(m.nextMarketPulse)||Date.now()+1000;if(!m.fairProbabilities||!m.preMatchFacts){const h=[m.home,m.homeAttack,m.homeDefense],a=[m.away,m.awayAttack,m.awayDefense],model=factualModel(h,a,m.id);m.fairProbabilities=model.probabilities;m.preMatchFacts=model.facts;}return m;}
function sanitizeTickets(s){if(!Array.isArray(s.tickets))s.tickets=[];s.tickets=s.tickets.filter(t=>t&&Array.isArray(t.picks)&&typeof t.status==='string');}
function refundObsoleteTickets(s,oldMatches){const ids=new Set(oldMatches.map(m=>m?.id));s.tickets.forEach(t=>{if(t.status==='ACTIVE'&&t.picks.some(p=>ids.has(p.matchId))){t.status='CANCELLED';t.payout=t.stake;s.tokens+=Number(t.stake)||0;}});}
function ensure(){const s=WLState.data,old=Array.isArray(s.matches)?s.matches:[];sanitizeTickets(s);if(s.scheduleVersion!==3||hasTeamConflicts(old)){refundObsoleteTickets(s,old);s.matches=createInitialSchedule();s.selections={};s.scheduleVersion=3;}else{const valid=old.filter(isValidMatch).map(normalizeMatch);s.matches=valid.slice(0,4);while(s.matches.length<4)s.matches.push(createMatch(s.matches.length,nextScheduledStart(s.matches),s.matches));}if(!s.feedMatchId||!s.matches.some(m=>m.id===s.feedMatchId))s.feedMatchId=(s.matches.find(m=>m.status==='LIVE')||s.matches[0])?.id||'';}
window.WLMatches={createMatch,createInitialSchedule,nextScheduledStart,ensure,isValidMatch,normalizeMatch,oddFromProbability,clamp,MATCH_DURATION,hasTeamConflicts,busyTeamNames,factualModel,teamFacts};
})();
