(()=>{'use strict';
const $=id=>document.getElementById(id),fmt=n=>Math.floor(Number(n)||0).toLocaleString('ru-RU'),labels={P1:'П1',X:'Ничья',P2:'П2'};let toastTimer;const openAnalysis=new Set();let feedFilter='all',ticketTab='active',feedContentKey='';
function marketLabel(k,short=false){return window.WLMarkets?WLMarkets.label(k,short):(labels[k]||k);}
function marketOdd(m,k){return window.WLMarkets?WLMarkets.odd(m,k):Number(m.odds?.[k]);}
function marketTrend(m,k){return window.WLMarkets?WLMarkets.trend(m,k):Number(m.oddsTrend?.[k]||0);}
function trendIcon(m,k){const t=marketTrend(m,k);return t<0?'<span class="odd-trend down">▼</span>':t>0?'<span class="odd-trend up">▲</span>':'<span class="odd-trend flat">•</span>';}
function timeLeft(m){if(m.status==='FINISHED')return'Завершён';const now=Date.now();if(m.status==='UPCOMING'||now<m.start){const sec=Math.max(0,Math.ceil((m.start-now)/1000));return`Начало через ${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;}const sec=Math.max(0,Math.ceil((m.end-now)/1000));return`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;}
function marketStageText(m){if(!window.WLMarkets)return'';const st=WLMarkets.stage(m),now=Date.now();if(st==='collecting'){const sec=Math.max(0,Math.ceil((Number(m.marketOpenAt)-now)/1000));return`Линия откроется через ${sec}с`;}if(st==='opening')return'Формируются первые коэффициенты';if(st==='prematch')return`Принято ставок: ${m.publicBetVolume||0}`;if(st==='live')return`LIVE-рынок · всего ставок: ${m.publicBetVolume||0}`;if(st==='suspended')return`⏸ ${WLMarkets.suspensionReason(m)||'Рынок приостановлен'}`;return'Линия закрыта';}
function factsBlock(m){const f=m.preMatchFacts;if(!f)return'';const form=x=>x.form.map(v=>`<i class="form-${v}">${v==='W'?'✓':v==='D'?'—':'×'}</i>`).join('');const leaders=x=>(x.topPlayers||[]).slice(0,3).map((p,i)=>{const initials=String(p.name||'?').split(/\s+/).map(v=>v[0]).join('').slice(0,2);return`<div class="leader-card"><span class="leader-avatar">${initials}</span><b>${p.name}</b><em>${p.rating}</em><small>${i===0?'Ключевой игрок':i===1?'Лидер линии':'Игрок основы'}</small></div>`}).join('');
 const styleLabel={high_press:'Высокий прессинг',possession:'Контроль мяча',possession_press:'Владение + прессинг',compact_counter:'Компактная контратака',vertical:'Вертикальный футбол',counter:'Быстрые контратаки',compact:'Низкий блок',balanced:'Сбалансированный стиль'};
 const dna=name=>{const p=window.WLTeamBrain?.profile?.(name)||{};return{style:styleLabel[p.style]||'Сбалансированный стиль',tempo:Math.round((p.tempo||.7)*100),press:Math.round((p.press||.68)*100),risk:Math.round((p.risk||.56)*100)}};
 const team=(name,x,side)=>{const d=dna(name);return`<div class="team-facts ${side}"><div class="team-facts-head"><b>${name}</b><span>Рейтинг состава <strong>${x.lineupRating}</strong></span></div><div class="team-style-chip">${d.style}</div><div class="team-facts-form"><span>Форма</span>${form(x)}<small>${x.wins}/5 побед</small></div><div class="team-ratings"><span>Атака <b>${x.attack}</b></span><span>Защита <b>${x.defense}</b></span></div><div class="team-dna"><span>Темп <b>${d.tempo}</b></span><span>Прессинг <b>${d.press}</b></span><span>Риск <b>${d.risk}</b></span></div><div class="leaders-row">${leaders(x)||'<small>Нет данных состава</small>'}</div></div>`};return`<div class="prematch-facts">${team(m.home,f.home,'home')}<i class="facts-vs">VS</i>${team(m.away,f.away,'away')}</div>`;}
function toast(text){const e=$('toast');e.textContent=text;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1800);}
function top(){const s=WLState.data,L=WLEconomy.league(),now=Date.now(),fever=s.feverUntil>now;$('energy').textContent=fmt(s.energy);$('tokens').textContent=fmt(s.tokens);$('league').textContent=L.current[0];$('level').textContent=s.level;$('xpText').textContent=`${fmt(s.xp)} / ${fmt(WLEconomy.xpNeed())}`;$('xpBar').style.width=Math.min(100,s.xp/WLEconomy.xpNeed()*100)+'%';$('clickPower').textContent=`+${fmt(WLEconomy.clickValue())} за клик`;$('comboLabel').textContent=`COMBO ×${s.combo.toFixed(1)}`;$('boostButton').textContent=s.boostUntil>now?`🔥 Буст ×2: ${Math.ceil((s.boostUntil-now)/1000)}с`:'🔥 Буст ×2 — 500';$('dailyButton').disabled=now-s.lastDaily<86400000;const hype=fever?100:Math.round(s.hype||0);if($('hypeBar'))$('hypeBar').style.width=hype+'%';if($('hypeText'))$('hypeText').textContent=fever?`${Math.ceil((s.feverUntil-now)/1000)}с`:hype+'%';if($('feverStatus'))$('feverStatus').textContent=fever?'🔥 ТРИБУНЫ В ОГНЕ · ×3':'Разогрейте трибуны';const passive=WLEconomy.passiveValue?WLEconomy.passiveValue():s.passive;if($('passiveRate'))$('passiveRate').textContent='+'+fmt(passive);if($('critChance'))$('critChance').textContent=Math.round(WLEconomy.critChance()*100)+'%';if($('bestCombo'))$('bestCombo').textContent='×'+Number(s.bestCombo||1).toFixed(1);if($('totalClickStat'))$('totalClickStat').textContent=fmt(s.totalClicks);if($('criticalClickStat'))$('criticalClickStat').textContent=fmt(s.critClicks||0);if($('shopIncome'))$('shopIncome').textContent='+'+fmt(passive)+'/сек';document.querySelector('.hero')?.classList.toggle('fever-active',fever);}
function shop(){const s=WLState.data;$('shopList').innerHTML=WLShop.upgrades.map(u=>`<div class="item upgrade-card"><span class="upgrade-icon">${u.icon||'⬆️'}</span><div class="item-info"><b>${u.name}</b><span>${u.description}</span><small>Уровень ${s.upgrades[u.id]||0}</small></div><button data-buy="${u.id}" ${s.energy<WLShop.cost(u)?'disabled':''}>${fmt(WLShop.cost(u))}</button></div>`).join('');}
function prestige(){if(!window.WLPrestige)return;const p=WLPrestige.normalized(),req=WLPrestige.requirement(),run=WLPrestige.runScore(),gain=WLPrestige.reward();$('fameBalance').textContent=fmt(p.fame)+' славы';$('prestigeCount').textContent=fmt(p.count);$('runEnergy').textContent=fmt(run);$('prestigeRequirement').textContent=fmt(req);$('prestigeReward').textContent=fmt(gain);$('prestigeProgress').style.width=Math.min(100,run/req*100)+'%';$('rebirthButton').disabled=!WLPrestige.canRebirth();$('rebirthButton').textContent=gain?`👑 Переродиться · +${gain} славы`:'👑 Переродиться';$('talentList').innerHTML=WLPrestige.talents.map(t=>{const level=WLPrestige.level(t.id),max=level>=t.max,cost=WLPrestige.talentCost(t);return`<div class="item upgrade-card talent-card"><span class="upgrade-icon">${t.icon}</span><div class="item-info"><b>${t.name}</b><span>${t.description}</span><small>Уровень ${level} / ${t.max}</small></div><button data-talent="${t.id}" ${max||p.fame<cost?'disabled':''}>${max?'MAX':fmt(cost)+' славы'}</button></div>`}).join('');}
function quests(){const s=WLState.data,q=[['100 кликов',s.quests.clicks,100,300,'q1'],['5 улучшений',s.quests.buys,5,600,'q2'],['3 прогноза',s.quests.predictions,3,300,'q3']];$('questList').innerHTML=q.map(x=>`<div class="item"><div class="item-info"><b>${x[0]}</b><span>${Math.min(x[1],x[2])}/${x[2]} · ${x[3]} энергии</span></div><button data-q="${x[4]}" data-r="${x[3]}" ${x[1]<x[2]||s.claimed[x[4]]?'disabled':''}>${s.claimed[x[4]]?'Получено':'Забрать'}</button></div>`).join('');}
function homeLive(){$('homeLive').innerHTML=WLState.data.matches.slice(0,3).map(m=>`<div class="match-option"><div class="match-meta"><b>${m.home} — ${m.away}</b><span class="match-clock">${timeLeft(m)}</span></div><div class="match-score">${m.status==='UPCOMING'?'—':m.scoreH+':'+m.scoreA}</div></div>`).join('');}
function analyticsBlock(m){
 const a=window.WLAnalytics?.ensure(m);if(!a)return'';
 const L=WLAnalytics.LABELS,prob=k=>Math.round(a.probabilities[k]*100),valueClass=n=>n>=8?'positive':n<0?'negative':'neutral';
 return`<div class="prediction-center">
  <div class="prediction-head"><div><span class="prediction-kicker">AI SCOUT</span><b>${L[a.scoutPick]} · ${a.confidence}/100</b></div><span class="difficulty difficulty-${a.difficulty}">${a.difficulty}</span></div>
  <div class="confidence-bar"><i style="width:${a.confidence}%"></i></div>
  <div class="prediction-grid">
   <div class="analysis-card scout-card"><span>Прогноз ИИ</span><strong>${L[a.scoutPick]}</strong><small>${WLAnalytics.stars(a.confidence)}</small></div>
   <div class="analysis-card"><span>Мнение игроков</span><strong>${L[a.crowdTop]} ${a.crowd[a.crowdTop]}%</strong><small>П1 ${a.crowd.P1}% · Х ${a.crowd.X}% · П2 ${a.crowd.P2}%</small></div>
   <div class="analysis-card smart-card"><span>Smart Money</span><strong>${L[a.smartMoney]}</strong><small>${a.smartMoney!==a.crowdTop?'⚠ Против большинства':'Совпадает с рынком'}</small></div>
   <div class="analysis-card value-card"><span>Лучший Value</span><strong>${L[a.bestValue]}</strong><small class="value-${valueClass(a.value[a.bestValue])}">${a.value[a.bestValue]>=0?'+':''}${a.value[a.bestValue]}%</small></div>
  </div>
  <details class="analysis-details" data-analysis-id="${m.id}" ${openAnalysis.has(m.id)?'open':''}><summary>Открыть полный разбор</summary>
   <div class="probability-bars">${['P1','X','P2'].map(k=>`<div><span>${L[k]}</span><i><b style="width:${prob(k)}%"></b></i><em>${prob(k)}%</em><small class="value-${valueClass(a.value[k])}">Value ${a.value[k]>=0?'+':''}${a.value[k]}%</small></div>`).join('')}</div>
   <div class="reasons"><b>Почему такой прогноз</b>${a.reasons.map(x=>`<span>✓ ${x}</span>`).join('')}</div>
   <div class="analysts">${a.analysts.map(x=>`<div><span>${x.name}</span><b>${L[x.pick]}</b><small>${x.confidence}/100 · точность ${x.accuracy}%</small></div>`).join('')}</div>
   ${a.flags.length?`<div class="analysis-alerts">${a.flags.map(x=>`<span>⚡ ${x}</span>`).join('')}</div>`:''}
  </details>
 </div>`;
}
function matches(){const s=WLState.data;$('matchesList').innerHTML=s.matches.map(m=>{if(window.WLMarkets)WLMarkets.ensure(m);const gate=window.WLMarkets?WLMarkets.canBet(m):{ok:m.status!=='FINISHED'},marketReady=gate.ok,locked=!gate.ok,active=Number(m.marketActivityUntil||0)>Date.now();const groups=[['Основные',['P1','X','P2']],['Двойной шанс',['1X','12','X2']],['Тоталы',['O15','U15','O25','U25']],['Голы',['BTTS_Y','BTTS_N','H_O05','A_O05']]];return`<div class="match-option ${active?'market-active':''}"><div class="match-meta"><div><span class="live-badge ${m.status==='UPCOMING'?'upcoming-badge':''}">${m.status==='LIVE'?'● LIVE':m.status==='UPCOMING'?'◷ СКОРО':'FINISHED'}</span> <span class="match-clock">${timeLeft(m)}</span><span class="market-stage">${marketStageText(m)}</span>${active?`<span class="market-activity">+${m.lastBetBatch||0} за последние секунды</span>`:''}${m.market?.label?`<span class="market-sentiment">${m.market.label}</span>`:''}<div class="teams-line"><span>${m.home}</span><span>—</span><span>${m.away}</span></div></div><div class="match-score">${m.status==='UPCOMING'?'—':m.scoreH+':'+m.scoreA}</div></div><div class="market-sections">${groups.map((g,gi)=>`<div class="market-section ${gi?'market-extra':''}"><div class="market-group-title">${g[0]}</div><div class="market-grid market-grid-${g[1].length}">${g[1].map(k=>{const odd=marketOdd(m,k),trend=marketTrend(m,k);return`<button class="market ${s.selections[m.id]===k?'selected':''} trend-${trend}" data-mid="${m.id}" data-key="${k}" ${locked||!Number.isFinite(odd)?'disabled':''}>${marketLabel(k,true)}<br><b>${Number(odd||0).toFixed(2)} ${trendIcon(m,k)}</b></button>`}).join('')}</div></div>`).join('')}</div>${factsBlock(m)}${analyticsBlock(m)}</div>`;}).join('');$('feedMatch').innerHTML=s.matches.map(m=>`<option value="${m.id}" ${s.feedMatchId===m.id?'selected':''}>${m.home} — ${m.away}</option>`).join('');coupon();feed();} 
function coupon(){
 const s=WLState.data,ids=Object.keys(s.selections),box=$('coupon'),type=document.querySelector('input[name="ticketType"]:checked')?.value||'single';
 if(!ids.length){box.innerHTML='<div class="coupon-empty betslip-empty"><span>🎟️</span><b>Купон пуст</b><small>Выберите коэффициент в линии матча</small></div>';payout();return;}
 const picks=ids.map(id=>{const m=s.matches.find(x=>x.id===id),k=s.selections[id],odd=m?marketOdd(m,k):0,gate=m&&window.WLMarkets?WLMarkets.canBet(m):{ok:true};if(!m)return'';return`<article class="betslip-pick ${gate.ok?'':'locked'}"><button class="remove-pick" data-remove="${id}" aria-label="Удалить ставку">×</button><div class="betslip-match"><span>${m.status==='LIVE'?'● LIVE':m.status==='UPCOMING'?'◷ ДО МАТЧА':'ЗАВЕРШЁН'}</span><b>${m.home} — ${m.away}</b></div><div class="betslip-selection"><div><small>Выбранный рынок</small><strong>${marketLabel(k)}</strong></div><em>${Number(odd||0).toFixed(2)}</em></div>${gate.ok?'':`<div class="betslip-warning">⏸ ${gate.reason||'Рынок временно недоступен'}</div>`}</article>`;}).join('');
 const total=WLCoupon.combinedOdd();box.innerHTML=`<div class="betslip-head"><span>${type==='express'?'Экспресс':'Одиночная ставка'}</span><b>${ids.length} ${ids.length===1?'событие':'события'}</b></div>${picks}<div class="betslip-total"><span>Общий коэффициент</span><strong>${total.toFixed(2)}</strong></div>`;payout();
}
function payout(){const stake=Math.max(0,Number($('stakeInput').value)||0),odd=WLCoupon.combinedOdd(),pay=Math.floor(stake*odd),profit=Math.max(0,pay-stake),s=WLState.data;const pp=$('potentialPayout'),profitEl=$('potentialProfit'),balanceEl=$('balanceAfter'),button=$('placePredictionButton');if(pp)pp.textContent=fmt(pay);if(profitEl)profitEl.textContent=fmt(profit);if(balanceEl)balanceEl.textContent=fmt(Math.max(0,s.tokens-stake));if(button){button.disabled=!Object.keys(s.selections).length||stake<10||stake>s.tokens;button.innerHTML=stake>=10?`Поставить ${fmt(stake)}<small>Выплата ${fmt(pay)}</small>`:'Подтвердить прогноз';}}
function finalMatchCard(){
 const s=WLState.data,m=s.matches.find(x=>x.id===s.feedMatchId)||s.matches[0],box=$('finalMatchCard');
 if(!box)return;
 if(!m||m.status!=='FINISHED'){box.hidden=true;box.innerHTML='';return;}
 const st=m.finalStats||{},pom=m.playerOfMatch||{};
 box.hidden=false;
 box.innerHTML=`<div class="final-title">МАТЧ ЗАВЕРШЁН</div><div class="final-score"><span>${m.home}</span><b>${m.scoreH} : ${m.scoreA}</b><span>${m.away}</span></div><div class="final-stats"><div><span>Удары</span><b>${st.homeShots??0} — ${st.awayShots??0}</b></div><div><span>В створ</span><b>${st.homeOnTarget??0} — ${st.awayOnTarget??0}</b></div><div><span>Владение</span><b>${st.homePossession??50}% — ${st.awayPossession??50}%</b></div></div><div class="player-of-match">⭐ Герой матча: <b>${pom.name||'—'}</b>${pom.team?` · ${pom.team}`:''}${pom.rating?` · рейтинг ${pom.rating}`:''}${pom.details?`<small>${pom.details}</small>`:''}</div>${m.living?.personality?`<div class="match-personality">Характер матча: <b>${m.living.personality}</b></div>`:''}${m.summary?`<p>${m.summary}</p>`:''}`;
}
function eventMeta(text){const raw=String(text||''),u=raw.toUpperCase();if(u.includes('ГОЛ'))return{type:'goal',icon:'⚽',label:'ГОЛ',key:true};if(u.includes('КРАСН')||u.includes('🟥'))return{type:'red',icon:'🟥',label:'УДАЛЕНИЕ',key:true};if(u.includes('ЖЕЛТ')||u.includes('🟨'))return{type:'yellow',icon:'🟨',label:'КАРТОЧКА',key:true};if(u.includes('СЕЙВ')||u.includes('ВРАТАР'))return{type:'save',icon:'🧤',label:'СЕЙВ',key:true};if(u.includes('УДАР')||u.includes('ОПАСН')||u.includes('ШТАНГ')||u.includes('ПЕРЕКЛАД'))return{type:'chance',icon:'🎯',label:'МОМЕНТ',key:true};if(u.includes('ПЕРЕХВАТ')||u.includes('ОТБОР'))return{type:'duel',icon:'⚔️',label:'ЕДИНОБОРСТВО',key:false};if(u.includes('ФИНАЛЬНЫЙ СВИСТОК')||u.includes("90'"))return{type:'final',icon:'🏁',label:'ФИНАЛ',key:true};return{type:'normal',icon:'•',label:'ИГРА',key:false};}
function eventMinute(text){const m=String(text||'').match(/(^|\s)(\d{1,3})['’]/);return m?m[2]+"'":'LIVE';}
function feed(){
 const s=WLState.data,m=s.matches.find(x=>x.id===s.feedMatchId)||s.matches[0],box=$('liveFeed');
 if(!m){
  const emptyKey='empty';
  if(feedContentKey!==emptyKey){box.innerHTML='<div class="empty-state"><b>Событий пока нет</b><span>Выберите матч или дождитесь стартового свистка.</span></div>';feedContentKey=emptyKey;}
  return;
 }
 const status=$('feedLiveState');
 if(status){status.textContent=m.status==='LIVE'?'● LIVE':m.status==='FINISHED'?'ЗАВЕРШЁН':'СКОРО';status.className='feed-live-state '+m.status.toLowerCase();}
 const st=m.finalStats||m.liveStats||{};
 $('feedOverview').innerHTML=`<div class="feed-scoreline"><span>${m.home}</span><b>${m.status==='UPCOMING'?'—':m.scoreH+' : '+m.scoreA}</b><span>${m.away}</span></div><div class="feed-mini-stats"><span>Удары <b>${st.homeShots??m.stats?.homeShots??0} : ${st.awayShots??m.stats?.awayShots??0}</b></span><span>В створ <b>${st.homeOnTarget??m.stats?.homeOnTarget??0} : ${st.awayOnTarget??m.stats?.awayOnTarget??0}</b></span><span>Владение <b>${st.homePossession??50}% : ${st.awayPossession??50}%</b></span></div>`;
 const summary=m.status==='FINISHED'&&m.summary?`<details class="match-summary"><summary><span>📝 Итог матча</span><b>Открыть разбор</b></summary><p>${m.summary}</p></details>`:'';
 let events=Array.isArray(m.events)?m.events:[];
 events=events.filter(e=>{const meta=eventMeta(e);if(feedFilter==='goals')return meta.type==='goal';if(feedFilter==='cards')return meta.type==='yellow'||meta.type==='red';if(feedFilter==='key')return meta.key;return true;});
 const contentKey=[m.id,feedFilter,m.status,m.summary||'',events.length,events[0]||'',events[events.length-1]||''].join('|');
 if(feedContentKey!==contentKey){
  const oldScroll=box.scrollTop,wasNearBottom=box.scrollHeight-box.clientHeight-oldScroll<48;
  const lines=events.length?events.map((e,i)=>{const meta=eventMeta(e);return`<article class="feed-event event-${meta.type}" data-event-index="${i}"><div class="event-time">${eventMinute(e)}</div><div class="event-marker">${meta.icon}</div><div class="event-body"><span class="event-type">${meta.label}</span><p>${String(e).replace(/^\s*\d{1,3}['’]\s*/,'')}</p></div></article>`}).join(''):'<div class="empty-state"><b>В этой категории событий нет</b><span>Попробуйте выбрать другой фильтр.</span></div>';
  const tpl=document.createElement('template');tpl.innerHTML=summary+`<div class="feed-timeline">${lines}</div>`;
  box.replaceChildren(tpl.content.cloneNode(true));
  requestAnimationFrame(()=>{box.scrollTop=wasNearBottom?box.scrollHeight:Math.min(oldScroll,Math.max(0,box.scrollHeight-box.clientHeight));});
  feedContentKey=contentKey;
 }
 finalMatchCard();
}
function ticketState(t){return t.status==='ACTIVE'?'active':t.status==='WON'?'won':'lost';}
function ticketProgress(t){if(t.status!=='ACTIVE')return'';const picks=t.picks||[],done=picks.filter(p=>{const m=WLState.data.matches.find(x=>x.id===p.matchId);return m&&m.status==='FINISHED';}).length;return`<div class="ticket-progress"><i style="width:${picks.length?Math.round(done/picks.length*100):0}%"></i></div><small>${done} из ${picks.length} событий завершено</small>`;}
function history(){const s=WLState.data,all=s.tickets.slice().reverse(),active=all.filter(t=>t.status==='ACTIVE'),settled=all.filter(t=>t.status!=='ACTIVE'),list=ticketTab==='active'?active:settled;$('activeTicketCount').textContent=active.length;$('settledTicketCount').textContent=settled.length;$('ticketSummary').textContent=`${active.length} активных · ${settled.length} завершённых`;$('historyList').innerHTML=list.length?list.map(t=>{const state=ticketState(t),potential=t.status==='ACTIVE'?Math.floor(t.stake*t.totalOdds):t.payout||0;return`<article class="ticket-card ticket-${state}"><header><div><span class="ticket-status">${state==='active'?'● В ИГРЕ':state==='won'?'✓ ВЫИГРЫШ':'× ПРОИГРЫШ'}</span><b>${t.picks.length>1?'Экспресс '+t.picks.length:'Одиночная ставка'}</b></div><strong>${Number(t.totalOdds||0).toFixed(2)}</strong></header><div class="ticket-picks">${t.picks.map(p=>`<div><span>${p.title}</span><b>${marketLabel(p.market)}</b></div>`).join('')}</div>${ticketProgress(t)}<footer><span>Ставка <b>${fmt(t.stake)}</b></span><span>${t.status==='ACTIVE'?'Возможная выплата':'Выплата'} <b>${fmt(potential)}</b></span></footer></article>`}).join(''):`<div class="empty-state"><b>${ticketTab==='active'?'Нет активных купонов':'История пока пуста'}</b><span>${ticketTab==='active'?'Сделайте прогноз, и он появится здесь.':'Завершённые ставки будут отображаться в этом разделе.'}</span></div>`;}
function profile(){const s=WLState.data,L=WLEconomy.league();$('profileStats').innerHTML=[['Энергия',fmt(s.energy)],['Жетоны',fmt(s.tokens)],['Рейтинг',fmt(s.rating)],['Лига',L.current[0]],['Слава',fmt(s.prestige?.fame||0)],['Перерождения',fmt(s.prestige?.count||0)],['Клики',fmt(s.totalClicks)],['Критические клики',fmt(s.critClicks||0)],['Лучшее комбо','×'+Number(s.bestCombo||1).toFixed(1)],['Победы',s.stats.won],['Поражения',s.stats.lost],['Лучший выигрыш',fmt(s.stats.bestWin)]].map(x=>`<div class="profile-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('badges').innerHTML=s.badges.map(b=>`<span class="badge-chip">🏅 ${b}</span>`).join('');$('achievementList').innerHTML=WLProfile.achievements().map(x=>`<div class="item"><div class="item-info"><b>${x[1]?'✅':'🔒'} ${x[0]}</b></div></div>`).join('');}
function render(){if(WLState.data.comboExpires<Date.now())WLState.data.combo=1;top();shop();prestige();quests();homeLive();matches();history();profile();finalMatchCard();if(window.WLVisualizer)WLVisualizer.render();}

document.addEventListener('click',e=>{const ff=e.target.closest?.('[data-feed-filter]');if(ff){feedFilter=ff.dataset.feedFilter;document.querySelectorAll('[data-feed-filter]').forEach(b=>b.classList.toggle('active',b===ff));feed();return;}const tt=e.target.closest?.('[data-ticket-tab]');if(tt){ticketTab=tt.dataset.ticketTab;document.querySelectorAll('[data-ticket-tab]').forEach(b=>b.classList.toggle('active',b===tt));history();}});
document.addEventListener('toggle',e=>{const d=e.target;if(d?.classList?.contains('analysis-details')){const id=d.dataset.analysisId;if(d.open)openAnalysis.add(id);else openAnalysis.delete(id);}},true);
window.WLUI={render,toast,payout,timeLeft,fmt};
})();
