(()=>{'use strict';
function formatReward(value){const n=Number(value)||0;return Math.max(0,Math.round(n)).toLocaleString('ru-RU');}
function spawnFloat(event,text,cls=''){const d=document.createElement('div');d.className='float-number '+cls;d.textContent=text;d.style.left=(event?.clientX||innerWidth/2)+'px';d.style.top=(event?.clientY||innerHeight/2)+'px';document.body.appendChild(d);setTimeout(()=>d.remove(),900);}
function performClick(event,options={}){const s=WLState.data,now=Date.now(),windowMs=1350+(s.upgrades.drums||0)*90;s.combo=now<=s.comboExpires?Math.min(8,s.combo+.10+(s.upgrades.drums||0)*.01):1;s.comboExpires=now+windowMs;s.lastClickAt=now;s.bestCombo=Math.max(s.bestCombo||1,s.combo);let value=WLEconomy.clickValue(),critical=Math.random()<WLEconomy.critChance();value*=Number(options.rewardMultiplier||1);if(critical){value*=3;s.critClicks=(s.critClicks||0)+1;}const hypeBonus=window.WLPrestige?WLPrestige.bonus('fever',.08):1;s.hype=Math.min(100,(s.hype||0)+(4.2+(s.upgrades.ultras||0)*.7)*hypeBonus);if(s.hype>=100&&s.feverUntil<=now){s.feverUntil=now+12000+(s.upgrades.ultras||0)*1500;s.hype=0;setTimeout(()=>window.WLUI?.toast('🔥 ТРИБУНЫ В ОГНЕ — ×3!'),0);}s.energy+=value;s.totalEnergy+=value;s.totalEnergyRun=(s.totalEnergyRun||0)+value;s.totalClicks++;s.quests.clicks++;s.rhythm=Object.assign({hits:0,misses:0,perfect:0,good:0,late:0,sliders:0,holds:0},s.rhythm||{});if(options.active){s.rhythm.hits++;const k=String(options.accuracy||'').toLowerCase();if(k in s.rhythm)s.rhythm[k]++;if(options.accuracy==='SLIDER')s.rhythm.sliders++;if(options.accuracy==='HOLD')s.rhythm.holds++;}WLEconomy.addXp(critical?3:1);if(options.showFloat!==false)spawnFloat(event,(critical?'КРИТ! +':'+')+formatReward(value),critical?'critical':'');return{value,critical};}
function miss(){const s=WLState.data;s.combo=1;s.comboExpires=0;s.hype=Math.max(0,(s.hype||0)-12);s.rhythm=Object.assign({hits:0,misses:0,perfect:0,good:0,late:0,sliders:0,holds:0},s.rhythm||{});s.rhythm.misses++;}
function triggerEvent(){const s=WLState.data,now=Date.now(),roll=Math.random(),fortune=window.WLPrestige?WLPrestige.eventRewardMultiplier():1;let message='';if(roll<.38){const reward=Math.floor((250+s.level*60)*fortune);s.energy+=reward;s.totalEnergy+=reward;s.totalEnergyRun=(s.totalEnergyRun||0)+reward;s.clickerEvent={nextAt:now+90000+Math.random()*90000,activeUntil:0,type:'sponsor',multiplier:1};message=`💰 Спонсор клуба: +${reward} энергии`;}else if(roll<.72){s.clickerEvent={nextAt:now+90000+Math.random()*90000,activeUntil:now+30000,type:'fans',multiplier:2};message='📣 Фанаты в экстазе: ×2 к кликам на 30 секунд';}else{const reward=Math.max(1,Math.floor((1+s.level/10)*fortune));s.tokens+=reward*10;s.clickerEvent={nextAt:now+90000+Math.random()*90000,activeUntil:0,type:'gift',multiplier:1};message=`🎁 Подарок клуба: +${reward*10} жетонов`;}window.WLUI?.toast(message);}
function tick(){const s=WLState.data,now=Date.now();if(now>s.comboExpires)s.combo=1;if(now-s.lastClickAt>500&&(s.hype||0)>0&&s.feverUntil<=now)s.hype=Math.max(0,s.hype-.7);if(!s.clickerEvent)s.clickerEvent={nextAt:0,activeUntil:0,type:'',multiplier:1};if(!s.clickerEvent.nextAt)s.clickerEvent.nextAt=now+45000+Math.random()*45000;if(now>=s.clickerEvent.nextAt)triggerEvent();}
function buyBoost(){const s=WLState.data;if(s.energy<500)return false;s.energy-=500;s.boostUntil=Math.max(Date.now(),s.boostUntil)+60000;return true;}
function claimDaily(){const s=WLState.data;if(Date.now()-s.lastDaily<86400000)return false;s.lastDaily=Date.now();s.energy+=500+s.level*50;s.tokens+=200;return true;}
window.WLClicker={performClick,miss,tick,buyBoost,claimDaily,triggerEvent};
})();