(()=>{'use strict';
const $=id=>document.getElementById(id),rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const LEVELS={
 novice:{name:'Новичок',reward:1,life:1420,gap:700,size:1.20,max:1,double:.03,weights:{tap:42,fast:12,doubletap:12,swipe:15,slider:6,spinner:7,golden:6}},
 amateur:{name:'Любитель',reward:1.30,life:1160,gap:535,size:1,max:2,double:.08,weights:{tap:34,fast:14,doubletap:15,swipe:18,slider:7,spinner:8,golden:4}},
 pro:{name:'Профи',reward:1.72,life:930,gap:425,size:.88,max:2,double:.13,weights:{tap:27,fast:16,doubletap:18,swipe:21,slider:7,spinner:8,golden:3}},
 expert:{name:'Эксперт',reward:2.30,life:760,gap:345,size:.77,max:2,double:.18,weights:{tap:21,fast:18,doubletap:20,swipe:23,slider:7,spinner:9,golden:2}},
 legend:{name:'Легенда',reward:3.05,life:640,gap:285,size:.68,max:2,double:.23,weights:{tap:17,fast:19,doubletap:22,swipe:24,slider:7,spinner:9,golden:2}}
};
const SIMPLE_TYPES=new Set(['tap','fast','golden']);
const EXCLUSIVE_TYPES=new Set(['spinner','swipe','slider','doubletap']);
const MODIFIERS={
 speed:{label:'⚡ Быстрее',reward:.18},small:{label:'🎯 Меньше цели',reward:.25},swipes:{label:'🌀 Больше свайпов',reward:.20},doubletap:{label:'👆 Больше двойных',reward:.18},nomiss:{label:'🔥 Без права на ошибку',reward:.50},golden:{label:'⭐ Больше золотых',reward:.10}
};
const state={running:false,mode:'active',difficulty:'amateur',modifiers:new Set(),targets:new Map(),pointers:new Map(),nextTimer:null,sessionTimer:null,id:0,endAt:0,startedAt:0,stats:null,episode:null,nextEpisodeAt:0,phase:'Разминка',lastMilestone:0};
function field(){return $('rhythmField')} function level(){return LEVELS[state.difficulty]||LEVELS.amateur}
function modifierReward(){let v=1;state.modifiers.forEach(k=>v+=MODIFIERS[k]?.reward||0);return v}
function sessionProgress(){return state.running?clamp((Date.now()-state.startedAt)/60000,0,1):0}
function phaseData(){const p=sessionProgress();if(p<.25)return{name:'РАЗМИНКА',life:1.10,gap:1.12,reward:1};if(p<.55)return{name:'ТЕМП',life:.96,gap:.92,reward:1.08};if(p<.82)return{name:'ГОРЯЧАЯ СЕРИЯ',life:.84,gap:.78,reward:1.18};return{name:'ФИНАЛЬНЫЙ РЫВОК',life:.72,gap:.64,reward:1.35}}
function adaptiveFactor(){const s=state.stats;if(!s||s.hits+s.misses<5)return 1;const acc=s.hits/(s.hits+s.misses);return acc>.93?.90:acc<.68?1.10:1}
function config(){const l=level(),p=WLState.data.prestige?.count||0,ph=phaseData(),ad=adaptiveFactor(),speed=state.modifiers.has('speed')?.80:1,small=state.modifiers.has('small')?.76:1;return{life:Math.max(390,(l.life-p*12)*ph.life*ad*speed),gap:Math.max(180,(l.gap-p*5)*ph.gap*ad*speed),size:Math.max(40,(86*l.size-p*.35)*small),phaseReward:ph.reward}}
function summary(){const l=level(),m=modifierReward();return`${l.name}: базовая ×${l.reward.toFixed(2)} · итоговая ×${(l.reward*m).toFixed(2)}`}
function setMode(mode){state.mode=mode==='lazy'?'lazy':'active';document.querySelectorAll('[data-clicker-mode]').forEach(b=>b.classList.toggle('active',b.dataset.clickerMode===state.mode));const a=$('activeMode'),z=$('lazyMode');if(a){a.hidden=state.mode!=='active';a.style.display=state.mode==='active'?'block':'none'}if(z){z.hidden=state.mode!=='lazy';z.style.display=state.mode==='lazy'?'flex':'none'}if(state.mode!=='active')stopSession(false)}
function setDifficulty(key){if(state.running||!LEVELS[key])return;state.difficulty=key;document.querySelectorAll('[data-difficulty]').forEach(b=>b.classList.toggle('active',b.dataset.difficulty===key));$('trainingEpisode').textContent=summary()}
function toggleModifier(key){if(state.running||!MODIFIERS[key])return;state.modifiers.has(key)?state.modifiers.delete(key):state.modifiers.add(key);document.querySelectorAll('[data-modifier]').forEach(b=>b.classList.toggle('active',state.modifiers.has(b.dataset.modifier)));$('trainingEpisode').textContent=summary()}
function resetStats(){state.stats={hits:0,misses:0,perfect:0,good:0,late:0,swipes:0,doubletaps:0,spinners:0,spinnerTurns:0,energy:0,bestCombo:0,episodes:0,reactionTotal:0,reactionCount:0,golden:0}}
function startSession(){if(state.running||state.mode!=='active')return;resetStats();state.running=true;state.startedAt=Date.now();state.endAt=state.startedAt+60000;state.lastMilestone=0;state.nextEpisodeAt=Date.now()+rand(6500,9500);field()?.classList.remove('paused');$('trainingResult').hidden=true;$('trainingStartButton').disabled=true;$('trainingStartButton').textContent='Тренировка идёт';document.querySelectorAll('[data-difficulty],[data-modifier]').forEach(b=>b.disabled=true);tick();schedule(180)}
function stopSession(show=true){state.running=false;clearTimeout(state.nextTimer);clearInterval(state.sessionTimer);[...state.targets.values()].forEach(t=>removeTarget(t,false));state.pointers.clear();field()?.classList.add('paused');$('trainingStartButton').disabled=false;$('trainingStartButton').textContent='▶ Начать';document.querySelectorAll('[data-difficulty],[data-modifier]').forEach(b=>b.disabled=false);if(show&&state.stats)showResults()}
function tick(){clearInterval(state.sessionTimer);const run=()=>{const left=Math.max(0,state.endAt-Date.now()),s=Math.ceil(left/1000),ph=phaseData();$('trainingTimer').textContent=`00:${String(s).padStart(2,'0')}`;if(state.phase!==ph.name){state.phase=ph.name;showEpisode(ph.name);field()?.classList.remove('phase-warmup','phase-tempo','phase-hot','phase-final');field()?.classList.add(ph.name==='РАЗМИНКА'?'phase-warmup':ph.name==='ТЕМП'?'phase-tempo':ph.name==='ГОРЯЧАЯ СЕРИЯ'?'phase-hot':'phase-final')}const pi=$('trainingPhase');if(pi)pi.textContent=ph.name;if(left<=0)stopSession(true)};run();state.sessionTimer=setInterval(run,200)}
function schedule(ms){clearTimeout(state.nextTimer);state.nextTimer=setTimeout(spawnWave,ms)}
function weightedChoice(weights,allowSwipe=true,allowed=null){const w={...weights};if(!allowSwipe)w.swipe=0;if(state.modifiers.has('swipes')){w.swipe*=1.8;w.slider*=1.35}if(state.modifiers.has('doubletap'))w.doubletap*=2;if(state.modifiers.has('golden'))w.golden*=3;if(allowed)for(const k of Object.keys(w))if(!allowed.has(k))w[k]=0;const total=Object.values(w).reduce((a,b)=>a+b,0);if(total<=0)return'tap';let r=Math.random()*total;for(const [k,v] of Object.entries(w)){r-=v;if(r<=0)return k}return'tap'}
function chooseType(allowSwipe=true,allowed=null){return weightedChoice(level().weights,allowSwipe,allowed)}
function isExclusive(type){return EXCLUSIVE_TYPES.has(type)}
function nextWaveDelay(){const c=config();return Math.max(120,c.gap+rand(55,125))}
function chooseSwipeShape(){const r=Math.random();return r<.30?'straight':r<.56?'diagonal':r<.80?'corner':'uturn'}
function circleScale(){const r=Math.random();return r<.22?.68:r<.72?1:r<.92?1.22:1.42}
function svgPath(shape,w,h,reverse){const p=34,m=h/2;let d,label;if(shape==='straight'){d=`M ${p} ${m} L ${w-p} ${m}`;label='ПРЯМОЙ'}else if(shape==='diagonal'){const up=Math.random()<.5;d=up?`M ${p} ${h-p} L ${w-p} ${p}`:`M ${p} ${p} L ${w-p} ${h-p}`;label='ДИАГОНАЛЬ'}else if(shape==='corner'){const up=Math.random()<.5,x=Math.round(w*rand(.44,.58));d=up?`M ${p} ${h-p} L ${x} ${h-p} L ${x} ${p} L ${w-p} ${p}`:`M ${p} ${p} L ${x} ${p} L ${x} ${h-p} L ${w-p} ${h-p}`;label='УГЛОВОЙ'}else{d=`M ${p} ${m} L ${w-p} ${m} L ${p} ${m}`;label='ТУДА И ОБРАТНО'}return{d,label,transform:reverse?`translate(${w} 0) scale(-1 1)`:''}}
function overlaps(b){for(const t of state.targets.values()){const r=t.box;if(r&&!(b.x+b.w+12<r.x||r.x+r.w+12<b.x||b.y+b.h+12<r.y||r.y+r.h+12<b.y))return true}return false}
function findPosition(rect,w,h,m=14){for(let i=0;i<28;i++){const b={x:m+Math.random()*Math.max(1,rect.width-w-m*2),y:m+Math.random()*Math.max(1,rect.height-h-m*2),w,h};if(!overlaps(b))return b}return{x:m,y:m,w,h}}
function startEpisode(){const episodes=[{name:'КОНТРАТАКА',seq:['tap','swipe','fast']},{name:'ПЕНАЛЬТИ',seq:['doubletap','swipe']},{name:'УГЛОВОЙ',seq:['swipe','doubletap']},{name:'ЗАКРУЧЕННЫЙ УДАР',seq:['spinner','fast']}],e=episodes[Math.floor(Math.random()*episodes.length)];state.episode={...e,index:0};state.stats.episodes++;showEpisode(e.name);$('trainingEpisode').textContent=`Эпизод: ${e.name}`}
function showEpisode(text){const e=$('episodeBanner');if(!e)return;e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1000)}
function spawnWave(){if(!state.running||state.mode!=='active'||!field())return;if(Date.now()>=state.endAt)return stopSession(true);
// Новая волна начинается только после полного завершения предыдущей.
// Это гарантирует, что спиннер, свайп, слайдер и двойной тап никогда не конфликтуют между собой.
if(state.targets.size>0){schedule(75);return}
const l=level();if(!state.episode&&Date.now()>=state.nextEpisodeAt)startEpisode();let types=[];
if(state.episode){types=[state.episode.seq[state.episode.index++]];if(state.episode.index>=state.episode.seq.length){state.episode=null;state.nextEpisodeAt=Date.now()+rand(7000,11000);setTimeout(()=>{$('trainingEpisode').textContent=summary()},900)}}else{
 const first=chooseType(true);types=[first];
 // Одновременно разрешены только две простые одиночные цели. Любое упражнение,
 // требующее жеста или повторного касания, всегда занимает поле целиком.
 if(SIMPLE_TYPES.has(first)&&l.max>1&&Math.random()<l.double){const second=chooseType(false,SIMPLE_TYPES);types.push(second)}
}
types.forEach((t,i)=>spawnTarget(t,i*90));schedule(nextWaveDelay())}
function spawnTarget(type,delay=0){setTimeout(()=>{if(!state.running||!field()||state.targets.size>=level().max)return;const f=field(),rect=f.getBoundingClientRect(),cfg=config(),id=++state.id,el=document.createElement('div');let data={},box;el.className=`rhythm-target type-${type}`;el.dataset.id=id;if(type==='swipe'){const shape=chooseSwipeShape(),w=Math.min(rect.width-28,shape==='uturn'?220:shape==='corner'?255:shape==='diagonal'?235:215),h=shape==='straight'||shape==='uturn'?88:shape==='diagonal'?132:148;box=findPosition(rect,w,h);const reverse=Math.random()<.5,path=svgPath(shape,w,h,reverse);el.classList.add(`swipe-${shape}`);el.style.cssText=`left:${box.x}px;top:${box.y}px;width:${w}px;height:${h}px`;el.innerHTML=`<svg class="swipe-svg" viewBox="0 0 ${w} ${h}"><g transform="${path.transform}"><path class="swipe-path" d="${path.d}"></path><path class="swipe-progress" d="${path.d}"></path></g></svg><span class="swipe-start">⚽</span><span class="swipe-end">➜</span>${shape==='uturn'?'<span class="swipe-turn">↩</span>':''}<b>${path.label}</b>`;data={shape,reverse}}else if(type==='slider'){const w=Math.min(205,rect.width*.42),h=68;box=findPosition(rect,w,h);el.style.cssText=`left:${box.x}px;top:${box.y}px;width:${w}px;height:${h}px`;el.innerHTML='<i class="slider-track"></i><span class="slider-ball">⚽</span><b>ПРОВЕДИ</b>'}else if(type==='spinner'){const size=Math.min(190,Math.max(145,rect.width*.30));box=findPosition(rect,size,size);el.style.cssText=`left:${box.x}px;top:${box.y}px;width:${size}px;height:${size}px`;el.innerHTML='<span class="spinner-ring"></span><span class="spinner-ball">⚽</span><b>КРУТИ</b><em>0.0</em>';data={turns:0,lastAngle:null}}else{const sc=circleScale(),size=Math.round(cfg.size*(type==='fast'?.72:type==='golden'?.62:sc));box=findPosition(rect,size,size);el.classList.add(sc<.8?'target-small':sc>1.3?'target-xl':sc>1.1?'target-large':'target-medium');el.style.cssText=`left:${box.x}px;top:${box.y}px;width:${size}px;height:${size}px`;const icon=type==='fast'?'⚡':type==='golden'?'★':type==='doubletap'?'②':'⚽',label=type==='fast'?'БЫСТРО':type==='golden'?'ЗОЛОТАЯ ЦЕЛЬ':type==='doubletap'?'ДВОЙНОЙ ТАП':'ЖМИ';el.innerHTML=`<span class="approach-ring"></span><span class="target-core">${icon}</span><b>${label}</b>${type==='doubletap'?'<i class="double-count">0/2</i>':''}`}f.appendChild(el);const pathType=type==='slider'||type==='swipe',life=type==='fast'?cfg.life*.55:type==='golden'?cfg.life*.48:type==='doubletap'?cfg.life*1.12:type==='spinner'?cfg.life*2.35:pathType?cfg.life*1.34:cfg.life;el.style.setProperty('--target-life',`${life}ms`);const t={id,el,type,born:performance.now(),life,done:false,progress:0,taps:0,box,...data};state.targets.set(id,t);if(type==='swipe')prepareSwipe(t);requestAnimationFrame(()=>el.classList.add('live'));t.timer=setTimeout(()=>type==='spinner'?finishSpinner(t):miss(t,'Время вышло'),life)},delay)}
function prepareSwipe(t){t.path=t.el.querySelector('.swipe-path');t.progressPath=t.el.querySelector('.swipe-progress');t.pathLength=t.path.getTotalLength();t.progressPath.style.strokeDasharray=t.pathLength;t.progressPath.style.strokeDashoffset=t.pathLength;positionNodes(t)}
function pathPoint(t,p){const a=t.path.getPointAtLength(t.pathLength*clamp(p,0,1)),svg=t.el.querySelector('svg'),pt=svg.createSVGPoint();pt.x=a.x;pt.y=a.y;const s=pt.matrixTransform(t.path.parentNode.getCTM()).matrixTransform(svg.getScreenCTM());return{x:s.x,y:s.y}}
function positionNodes(t){const svg=t.el.querySelector('svg'),g=t.path.parentNode,local=p=>{const q=svg.createSVGPoint();q.x=p.x;q.y=p.y;const z=q.matrixTransform(g.getCTM());return{x:z.x,y:z.y}},a=local(t.path.getPointAtLength(0)),b=local(t.path.getPointAtLength(t.pathLength));for(const [sel,p] of [['.swipe-start',a],['.swipe-end',b]]){const n=t.el.querySelector(sel);n.style.left=p.x+'px';n.style.top=p.y+'px'}if(t.shape==='uturn'){t.el.querySelector('.swipe-end').style.display='none';const n=t.el.querySelector('.swipe-turn'),m=local(t.path.getPointAtLength(t.pathLength/2));n.style.left=m.x+'px';n.style.top=m.y+'px'}}
function accuracy(t){const r=(performance.now()-t.born)/t.life;return r<=.35?{label:'PERFECT',m:1.38}:r<=.7?{label:'GOOD',m:1}:{label:'LATE',m:.62}}
function hit(t,m=1,label){if(!t||t.done)return;t.done=true;const a=accuracy(t),reaction=performance.now()-t.born,cfg=config(),gold=t.type==='golden'?4.5:1,res=WLClicker.performClick({clientX:eventX(t),clientY:eventY(t)},{rewardMultiplier:m*a.m*level().reward*modifierReward()*cfg.phaseReward*gold,accuracy:a.label,active:true,showFloat:false});state.stats.hits++;state.stats[a.label.toLowerCase()]++;state.stats.energy+=res.value;state.stats.reactionTotal+=reaction;state.stats.reactionCount++;if(t.type==='golden')state.stats.golden++;if(t.type==='swipe')state.stats.swipes++;if(t.type==='doubletap')state.stats.doubletaps++;if(t.type==='spinner'){state.stats.spinners++;state.stats.spinnerTurns+=t.turns||0}state.stats.bestCombo=Math.max(state.stats.bestCombo,WLState.data.combo||1);const combo=Math.floor(WLState.data.combo||0);for(const mark of [25,50,75,100])if(combo>=mark&&state.lastMilestone<mark){state.lastMilestone=mark;showEpisode(mark===25?'В РИТМЕ!':mark===50?'НЕУДЕРЖИМЫЙ!':mark===75?'МАСТЕР!':'ЛЕГЕНДА!')}showJudge(label||a.label,res.value);removeTarget(t,true);WLUI.render()}
function miss(t,why){if(!t||t.done)return;t.done=true;state.stats.misses++;WLClicker.miss();showJudge('MISS',0,why);removeTarget(t,true);WLUI.render();if(state.modifiers.has('nomiss'))stopSession(true)}
function removeTarget(t,anim){clearTimeout(t.timer);state.targets.delete(t.id);for(const [k,v] of state.pointers)if(v.targetId===t.id)state.pointers.delete(k);if(anim){t.el.classList.add('resolved');setTimeout(()=>t.el.remove(),140)}else t.el.remove()}
function eventX(t){const r=t.el.getBoundingClientRect();return r.left+r.width/2}function eventY(t){const r=t.el.getBoundingClientRect();return r.top+r.height/2}
function showJudge(label,value,extra=''){const e=$('rhythmJudge'),n=Math.round(Number(value)||0).toLocaleString('ru-RU');e.className='rhythm-judge show '+label.toLowerCase().replace(/\s+/g,'-');e.innerHTML=`<b>${label}</b>${value?`<span>+${n}</span>`:''}${extra?`<small>${extra}</small>`:''}`;clearTimeout(showJudge.t);showJudge.t=setTimeout(()=>e.classList.remove('show'),500)}
function targetFromEvent(e){const el=e.target.closest('.rhythm-target');return el?state.targets.get(Number(el.dataset.id)):null}function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function onDown(e){const t=targetFromEvent(e);if(!t||t.done)return;e.preventDefault();t.el.setPointerCapture?.(e.pointerId);if(t.type==='tap')hit(t,1);else if(t.type==='golden')hit(t,1,'ЗОЛОТАЯ ЦЕЛЬ');else if(t.type==='fast')hit(t,1.75);else if(t.type==='doubletap'){const now=performance.now();if(t.taps===0){t.taps=1;t.firstTap=now;t.el.classList.add('tap-once');t.el.querySelector('.double-count').textContent='1/2';clearTimeout(t.doubleTimer);t.doubleTimer=setTimeout(()=>miss(t,'Второй тап слишком поздно'),360)}else if(now-t.firstTap<=360){clearTimeout(t.doubleTimer);hit(t,1.7,'ДВОЙНОЙ ТАП')}}else if(t.type==='slider'){t.progress=0;state.pointers.set(e.pointerId,{targetId:t.id});updateSlider(t,e)}else if(t.type==='swipe'){const r=t.el.querySelector('.swipe-start').getBoundingClientRect();if(distance({x:e.clientX,y:e.clientY},{x:r.left+r.width/2,y:r.top+r.height/2})>62)return;t.progress=0;state.pointers.set(e.pointerId,{targetId:t.id});updateSwipe(t,e)}else if(t.type==='spinner'){const r=t.el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;t.lastAngle=Math.atan2(e.clientY-cy,e.clientX-cx);state.pointers.set(e.pointerId,{targetId:t.id})}}
function onMove(e){const p=state.pointers.get(e.pointerId),t=p&&state.targets.get(p.targetId);if(!t)return;if(t.type==='slider')updateSlider(t,e);if(t.type==='swipe')updateSwipe(t,e);if(t.type==='spinner')updateSpinner(t,e)}
function updateSlider(t,e){const r=t.el.getBoundingClientRect(),p=clamp((e.clientX-r.left-24)/(r.width-48),0,1);t.progress=Math.max(t.progress,p);t.el.style.setProperty('--slide',p*100+'%');if(t.progress>=.92)hit(t,1.8,'SLIDER')}
function updateSwipe(t,e){let best={d:1e9,p:t.progress};for(let i=0;i<=34;i++){const p=Math.max(0,t.progress-.02)+(Math.min(1,t.progress+.16)-Math.max(0,t.progress-.02))*i/34,d=distance({x:e.clientX,y:e.clientY},pathPoint(t,p));if(d<best.d)best={d,p}}const tol=t.shape==='uturn'?68:t.shape==='corner'?66:64;if(best.d<=tol&&best.p+.015>=t.progress){t.progress=Math.max(t.progress,best.p);t.progressPath.style.strokeDashoffset=t.pathLength*(1-t.progress)}if(t.progress>=.95)hit(t,t.shape==='straight'?2.05:t.shape==='diagonal'?2.25:t.shape==='corner'?2.5:2.9,t.shape==='uturn'?'ТУДА И ОБРАТНО':t.shape.toUpperCase()+' SWIPE')}
function updateSpinner(t,e){const r=t.el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,a=Math.atan2(e.clientY-cy,e.clientX-cx);if(t.lastAngle!=null){let d=a-t.lastAngle;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;if(Math.abs(d)<1.25)t.turns+=Math.abs(d)/(Math.PI*2)}t.lastAngle=a;t.el.style.setProperty('--spin',`${t.turns*360}deg`);t.el.querySelector('em').textContent=t.turns.toFixed(1)}
function finishSpinner(t){if(!t||t.done)return;const turns=t.turns||0;if(turns<.75)return miss(t,'Слишком мало оборотов');hit(t,1.35+Math.min(4,turns)*.55,`СПИННЕР ×${turns.toFixed(1)}`)}
function onUp(e){const p=state.pointers.get(e.pointerId),t=p&&state.targets.get(p.targetId);state.pointers.delete(e.pointerId);if(!t)return;if(t.type==='slider'&&t.progress<.92)miss(t,'Слайдер не завершён');else if(t.type==='swipe'&&t.progress<.95)miss(t,'Свайп не завершён');else if(t.type==='spinner')t.lastAngle=null}
function rank(){const s=state.stats,total=s.hits+s.misses,acc=total?s.hits/total:0,p=s.hits?s.perfect/s.hits:0;return acc>=.96&&p>=.45?'S+':acc>=.91?'S':acc>=.83?'A':acc>=.72?'B':acc>=.58?'C':'D'}
function showResults(){const s=state.stats,total=s.hits+s.misses,acc=total?Math.round(s.hits/total*100):0,r=rank(),reaction=s.reactionCount?Math.round(s.reactionTotal/s.reactionCount):0,key='winclickRecord_v014_'+state.difficulty,old=JSON.parse(localStorage.getItem(key)||'{}'),record=Math.max(old.energy||0,Math.round(s.energy));localStorage.setItem(key,JSON.stringify({energy:record,rank:r,combo:Math.max(old.combo||0,s.bestCombo),accuracy:Math.max(old.accuracy||0,acc)}));const perfectMatch=s.misses===0&&s.hits>10,mods=[...state.modifiers].map(k=>MODIFIERS[k].label).join(', ')||'без модификаторов',e=$('trainingResult');e.hidden=false;e.innerHTML=`<div class="result-grade">${r}</div><div><b>${perfectMatch?'PERFECT TRAINING':'Тренировка завершена'}</b><span>${level().name} · ${mods} · рекорд ${record.toLocaleString('ru-RU')}</span></div><div class="result-grid"><span>Точность <b>${acc}%</b></span><span>Perfect <b>${s.perfect}</b></span><span>Промахи <b>${s.misses}</b></span><span>Лучшее комбо <b>×${s.bestCombo.toFixed(1)}</b></span><span>Реакция <b>${reaction} мс</b></span><span>Двойные тапы <b>${s.doubletaps}</b></span><span>Спиннеры <b>${s.spinners}</b></span><span>Обороты <b>${s.spinnerTurns.toFixed(1)}</b></span><span>Свайпы <b>${s.swipes}</b></span><span>Энергия <b>+${Math.round(s.energy).toLocaleString('ru-RU')}</b></span></div>`;$('trainingEpisode').textContent=perfectMatch?'Идеальная тренировка без промахов!':'Тренировка завершена — попробуйте изменить модификаторы'}
function lazyClick(e){const r=WLClicker.performClick(e,{rewardMultiplier:.38,accuracy:'LAZY',active:false,showFloat:false});showJudge('LAZY',r.value);WLUI.render()}
function init(){const f=field();if(!f)return;f.addEventListener('pointerdown',onDown);f.addEventListener('pointermove',onMove);f.addEventListener('pointerup',onUp);f.addEventListener('pointercancel',onUp);$('trainingStartButton')?.addEventListener('click',startSession);$('lazyClickButton')?.addEventListener('click',lazyClick);document.querySelectorAll('[data-clicker-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.clickerMode)));document.querySelectorAll('[data-difficulty]').forEach(b=>b.addEventListener('click',()=>setDifficulty(b.dataset.difficulty)));document.querySelectorAll('[data-modifier]').forEach(b=>b.addEventListener('click',()=>toggleModifier(b.dataset.modifier)));setMode('active');setDifficulty('amateur');document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running)stopSession(false)})}
window.WLRhythm={init,start:startSession,stop:stopSession,setMode,setDifficulty,toggleModifier,state};
})();
