(()=>{'use strict';
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
const TYPES={goal:5.5,assist:3.2,shot:0.7,save:1.25,interception:.72,tackle:.62,attack:.20,build_up:.12,key_pass:.62,pressing:.10,support:.06,miss:.12,blocked_shot:.85};
const personalities=['тактический','открытый','жёсткий','техничный','напряжённый'];
const opposite=s=>s==='home'?'away':'home';
function sideName(match,side){return side==='home'?match.home:match.away;}
function ensure(match){
 if(match.living&&match.living.version===2)return match.living;
 const seed=Math.abs(String(match.id||'').split('').reduce((a,c)=>a+c.charCodeAt(0),0));
 match.living={version:2,personality:personalities[seed%personalities.length],crowdEnergy:.12,momentum:{home:.5,away:.5},momentumWave:[],recent:[],episodes:[],currentEpisode:null,episodeCounter:0,threads:{homePressure:0,awayPressure:0,homeSaves:0,awaySaves:0,homeInterceptions:0,awayInterceptions:0},playerImpact:{},lastNarrativeAt:0,lastEventAt:0,lastSide:null};
 return match.living;
}
function inferType(text,meta={}){if(meta.eventKind)return meta.eventKind;const t=String(text);if(/ГОЛ/.test(t))return'goal';if(/отражает|сейв|спасает/i.test(t))return'save';if(/перехват/i.test(t))return'interception';if(/рядом со штангой|промах/i.test(t))return'miss';if(/блокирует удар/i.test(t))return'blocked_shot';if(/удар/i.test(t))return'shot';if(/давление|атак|штрафной/i.test(t))return'attack';if(/передач|разыгрывает|контролирует/i.test(t))return'build_up';return'possession';}
function inferSide(match,text,meta={}){if(meta.attackingSide==='home'||meta.attackingSide==='away')return meta.attackingSide;const t=String(text);if(t.includes(match.home)&&!t.includes(match.away))return'home';if(t.includes(match.away)&&!t.includes(match.home))return'away';return match.flow?.possession||'home';}
function actorFrom(match,side,meta,type){if(meta.actorName)return meta.actorName;if(meta.scorer)return meta.scorer;const team=sideName(match,side);const role=type==='save'?'GK':type==='interception'?'DF':type==='goal'||type==='shot'?'FW':'MF';const slot=window.WLTeamDB?.slot(team,role,1+Math.floor(Math.random()*(role==='GK'?1:role==='DF'?4:3)));return slot?.shortName||slot?.fullName||role;}
function episodeKind(type){if(type==='goal')return'goal_attack';if(['shot','save','miss','blocked_shot'].includes(type))return'chance';if(type==='interception')return'counter';if(['attack','build_up','possession','short_pass','support'].includes(type))return'build_up';return'phase';}
function updateEpisode(match,event){const l=ensure(match),now=Date.now(),kind=episodeKind(event.type);let ep=l.currentEpisode;const mustNew=!ep||now-ep.lastAt>15000||ep.side!==event.side||(event.type==='goal')||(ep.closed);
 if(mustNew){if(ep){ep.closed=true;l.episodes.push(ep);l.episodes=l.episodes.slice(-16);}ep={id:`ep_${++l.episodeCounter}`,side:event.side,kind,startedAt:now,lastAt:now,events:[],danger:0,closed:false};l.currentEpisode=ep;}
 ep.lastAt=now;ep.events.push({type:event.type,minute:event.minute,text:event.text,actor:event.actor});ep.events=ep.events.slice(-10);ep.danger=clamp(ep.danger+(TYPES[event.type]||.08),0,2);if(['goal','save','miss','blocked_shot'].includes(event.type))ep.closed=true;event.episodeId=ep.id;return ep;
}
function updateMomentum(match,event){const l=ensure(match),side=event.side,other=opposite(side),weight=TYPES[event.type]||.07;let own=l.momentum[side],opp=l.momentum[other];own=clamp(own+weight*.18,.08,.92);opp=clamp(opp-weight*.11,.08,.92);const sum=own+opp;l.momentum[side]=own/sum;l.momentum[other]=opp/sum;l.crowdEnergy=clamp(l.crowdEnergy*.78+Math.min(1,weight*1.3)*.22,0,1);l.momentumWave.push({at:Date.now(),home:l.momentum.home,away:l.momentum.away});l.momentumWave=l.momentumWave.slice(-40);}
function updateThreads(match,event){const l=ensure(match),side=event.side,prefix=side==='home'?'home':'away';if(['attack','build_up','shot','goal','blocked_shot','miss'].includes(event.type))l.threads[prefix+'Pressure']=(l.threads[prefix+'Pressure']||0)+1;if(event.type==='save')l.threads[prefix+'Saves']=(l.threads[prefix+'Saves']||0)+1;if(event.type==='interception')l.threads[prefix+'Interceptions']=(l.threads[prefix+'Interceptions']||0)+1;l.recent.push(event);l.recent=l.recent.slice(-24);l.lastSide=side;l.lastEventAt=Date.now();
 const impact=l.playerImpact[event.actor]||(l.playerImpact[event.actor]={name:event.actor,team:sideName(match,side),score:0,goals:0,assists:0,shots:0,saves:0,interceptions:0,blocks:0,keyPasses:0,actions:0});impact.score+=(TYPES[event.type]||.04)*10;impact.actions++;if(event.type==='goal')impact.goals++;if(event.type==='shot')impact.shots++;if(event.type==='save')impact.saves++;if(event.type==='interception'||event.type==='tackle')impact.interceptions++;if(event.type==='blocked_shot')impact.blocks++;if(event.type==='key_pass')impact.keyPasses++;if(event.meta?.assistName){const a=l.playerImpact[event.meta.assistName]||(l.playerImpact[event.meta.assistName]={name:event.meta.assistName,team:sideName(match,side),score:0,goals:0,assists:0,shots:0,saves:0,interceptions:0,blocks:0,keyPasses:0,actions:0});a.assists++;a.score+=32;a.actions++;}
}
function narrativeLine(match,event){const l=ensure(match),now=Date.now();if(now-l.lastNarrativeAt<7000&&event.type!=='goal')return'';const side=event.side,team=sideName(match,side),other=sideName(match,opposite(side)),p=side==='home'?'home':'away',pressure=l.threads[p+'Pressure']||0,ints=l.threads[p+'Interceptions']||0,saves=l.threads[p+'Saves']||0,minute=event.minute;
 let text='';if(event.type==='goal'&&minute>=75)text=`${minute}' 🎙️ ${team} находит решающий момент в самой напряжённой стадии встречи.`;else if(pressure>=5&&pressure%4===1)text=`${minute}' 📖 ${team} уже несколько минут удерживает ${other} под постоянным давлением.`;else if(ints>=3&&ints%3===0)text=`${minute}' 🧠 ${team} всё лучше читает передачи соперника и контролирует пространство.`;else if(saves>=3&&saves%3===0)text=`${minute}' 🧤 Вратарь ${team} становится одной из главных фигур этого матча.`;else if(minute>=82&&sideScore(match,side)<sideScore(match,opposite(side)))text=`${minute}' 🔥 ${team} рискует всё сильнее — времени на спасение матча почти не осталось.`;
 if(text)l.lastNarrativeAt=now;return text;
}
function sideScore(match,side){return side==='home'?match.scoreH:match.scoreA;}
function process(match,text,meta={}){const l=ensure(match),minute=Number((String(text).match(/^([0-9]+)/)||[])[1]||0),type=inferType(text,meta),side=inferSide(match,text,meta),actor=actorFrom(match,side,meta,type);const event={minute,type,side,actor,text:String(text),meta};updateEpisode(match,event);updateMomentum(match,event);updateThreads(match,event);const extra=narrativeLine(match,event);return{main:event.text,extra,meta:{...meta,living:true,episodeId:event.episodeId,actorName:actor,matchPersonality:l.personality,crowdEnergy:l.crowdEnergy}};}
function humanError(match,minute){const l=ensure(match),side=match.flow?.possession||'home',other=opposite(side),team=sideName(match,side),rival=sideName(match,other);const pressure=l.momentum[other]||.5;const chance=.025+pressure*.035;if(Math.random()>chance)return null;const role=Math.random()<.55?'MF':'DF',actor=window.WLTeamDB?.slot(team,role,1+Math.floor(Math.random()*(role==='DF'?4:3)))?.shortName||role;const winner=window.WLTeamDB?.slot(rival,'MF',1+Math.floor(Math.random()*3))?.shortName||'полузащитник';match.flow.possession=other;match.flow.phase='possession';match.flow.danger=5;return{ text:`${minute}' ⚠️ ${actor} неудачно обрабатывает мяч под давлением, и ${winner} возвращает владение ${rival}`, meta:{eventKind:'interception',attackingSide:other,sourceSide:side,interceptorSide:other,actorName:winner,humanError:true,lane:match.flow.lane||'center',carrierRole:'MF',receiverRole:'MF'} };}
function hero(match){const l=ensure(match),list=Object.values(l.playerImpact);if(!list.length)return null;list.sort((a,b)=>b.score-a.score);const h=list[0];return{team:h.team,name:h.name,shortName:h.name,role:h.goals?'FW':h.saves?'GK':h.interceptions?'DF':'MF',rating:Math.min(10,(6.2+h.score/18)).toFixed(1),details:[h.goals?`${h.goals} гол(а)`:null,h.saves?`${h.saves} сейв(а)`:null,h.interceptions?`${h.interceptions} перехват(а)`:null,h.shots?`${h.shots} удар(а)`:null].filter(Boolean).join(' · ')};}
function summary(match,base=''){const l=ensure(match),home=Math.round(l.momentum.home*100),away=100-home,dominant=home>away+8?match.home:away>home+8?match.away:null,personality=l.personality;let extra=`Матч получился ${personality}.`;if(dominant)extra+=` По совокупности эпизодов больше инициативы было у ${dominant}.`;const heroData=hero(match);if(heroData)extra+=` Главной фигурой встречи стал ${heroData.name} (${heroData.team}).`;return `${base} ${extra}`.trim();}
window.WLLivingMatch={ensure,process,humanError,hero,summary};
})();
