(()=>{'use strict';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const INTENTS={HOLD:'HOLD_POSITION',PRESS:'PRESS_BALL',COVER:'COVER_TEAMMATE',MARK:'MARK_OPPONENT',SUPPORT:'SUPPORT_OWNER',RUN:'RUN_IN_BEHIND',LANE:'BLOCK_PASSING_LANE',RETURN:'RETURN_TO_SHAPE',OFFER:'OFFER_PASS',TRACK:'TRACK_RUNNER',EVADE:'EVADE_PRESSURE',QUICK_PASS:'QUICK_PASS'};
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
function profile(p){if(p.aiProfile)return p.aiProfile;const h=hash(p.fullName||p.id);const roleBase=p.role==='GK'?82:p.role==='DF'?78:p.role==='MF'?84:80;p.aiProfile={footballIQ:clamp(roleBase+(h%17)-8,65,96),vision:clamp(72+((h>>4)%23),65,95),risk:clamp(.25+((h>>9)%56)/100,.22,.81),confidence:.55+((h>>15)%31)/100,positioning:clamp(68+((h>>18)%28),65,96),decisions:clamp(66+((h>>21)%30),64,96),anticipation:clamp(67+((h>>24)%29),65,96),aggression:clamp(45+((h>>27)%46),40,91),teamwork:clamp(65+((h>>11)%31),63,96)};return p.aiProfile;}
function predictedBall(ball){const a=ball?.action;if(!a)return{x:ball?.x??.5,y:ball?.y??.5};const target=typeof a.to==='function'?a.to():a.to;if(!target)return{x:ball.x,y:ball.y};const lead=.45+Math.min(.35,(a.progress||0)*.35);return{x:ball.x+(target.x-ball.x)*lead,y:ball.y+(target.y-ball.y)*lead};}
function roleBounds(player){const home=player.side==='home';if(player.role==='GK')return home?{x1:.035,x2:.16,y1:.30,y2:.70}:{x1:.84,x2:.965,y1:.30,y2:.70};if(player.role==='DF')return home?{x1:.10,x2:.49,y1:.07,y2:.93}:{x1:.51,x2:.90,y1:.07,y2:.93};if(player.role==='MF')return{x1:.24,x2:.76,y1:.06,y2:.94};return home?{x1:.40,x2:.90,y1:.05,y2:.95}:{x1:.10,x2:.60,y1:.05,y2:.95};}
function clampToRole(p,x,y){const b=roleBounds(p);return{x:clamp(x,b.x1,b.x2),y:clamp(y,b.y1,b.y2)};}
const dir=s=>s==='home'?1:-1;
function influenceAt(point,players){let v=0;for(const p of players){const radius=p.role==='GK'?.09:p.role==='DF'?.13:p.role==='MF'?.15:.12;const d=dist(point,p);if(d<radius)v+=(1-d/radius)*(profile(p).footballIQ/100);}return v;}
function freeSpaceCandidates(owner,team,opponents){const d=dir(owner.side),ys=[.18,.34,.5,.66,.82],xs=owner.role==='DF'?[.46,.55,.63]:owner.role==='MF'?[.56,.66,.74]:[.66,.76,.84];const out=[];for(const rx of xs)for(const y of ys){const x=owner.side==='home'?rx:1-rx;const pt={x,y};const pressure=influenceAt(pt,opponents);const support=influenceAt(pt,team)*.35;const forward=(x-owner.x)*d;out.push({x,y,score:forward*.9-pressure*.75+support*.18-Math.abs(y-owner.y)*.12});}return out.sort((a,b)=>b.score-a.score);}
function chooseSupportPoint(p,owner,team,opponents){const d=dir(p.side),prof=profile(p);const candidates=freeSpaceCandidates(owner,team,opponents).filter(c=>{const b=roleBounds(p);return c.x>=b.x1&&c.x<=b.x2&&c.y>=b.y1&&c.y<=b.y2;});const best=candidates[Math.min(candidates.length-1,prof.footballIQ>86?0:prof.footballIQ>76?1:2)]||{x:p.baseX,y:p.baseY};if(p.role==='FW'&&prof.risk>.55)best.x+=d*.05;if(p.role==='DF')best.x=owner.x-d*.24;return best;}
function nearest(list,target,exclude=null){let b=null,bd=Infinity;for(const p of list){if(p===exclude)continue;const dd=dist(p,target);if(dd<bd){b=p;bd=dd;}}return b;}
function selectPressers(defenders,ballPoint,phase,brain){const eligible=defenders.filter(p=>p.role!=='GK').map(p=>({p,d:dist(p,ballPoint),iq:profile(p).footballIQ})).sort((a,b)=>(a.d-a.iq*.0007)-(b.d-b.iq*.0007));const intensity=brain?.pressIntensity||.65;const count=brain?.mode==='HIGH_PRESS'?3:brain?.mode==='PRESS'||phase==='final_third'?2:1;return new Set(eligible.filter(x=>x.d<.24+intensity*.08).slice(0,count).map(x=>x.p));}
function defensiveTarget(p,ballPoint,attackers,pressers,defenders){
 const d=dir(p.side),prof=profile(p),goalX=p.side==='home'?.055:.945;
 if(p.role==='GK')return{x:p.baseX,y:clamp(.5+(ballPoint.y-.5)*.24,.32,.68)};
 if(pressers.has(p))return{x:ballPoint.x-d*(.024+prof.aggression/7000),y:ballPoint.y};
 const dangerous=attackers.slice().sort((a,b)=>Math.abs(a.x-goalX)-Math.abs(b.x-goalX));
 if(p.role==='DF'){
   const rank=defenders.filter(x=>x.role==='DF').sort((a,b)=>a.baseY-b.baseY).indexOf(p);
   const zones=[.16,.38,.62,.84],zoneY=zones[Math.max(0,rank)];
   const runner=dangerous.find(a=>Math.abs(a.y-zoneY)<.24)||dangerous[rank%dangerous.length];
   const shotLineY=runner?clamp((runner.y+ballPoint.y)*.5,.10,.90):zoneY;
   const lineX=clamp(p.baseX-d*(.018+(ballPoint.x-.5)*d*.035),roleBounds(p).x1,roleBounds(p).x2);
   return{x:lineX,y:clamp(zoneY*.62+shotLineY*.38,.09,.91)};
 }
 if(p.role==='MF'){
   const mates=defenders.filter(x=>x.role==='MF').sort((a,b)=>a.baseY-b.baseY),rank=mates.indexOf(p),zones=[.25,.50,.75],zoneY=zones[Math.max(0,rank)];
   const target=dangerous.find(a=>Math.abs(a.y-zoneY)<.28);
   return{x:clamp((ballPoint.x+(target?.x??p.baseX))/2-d*.055,roleBounds(p).x1,roleBounds(p).x2),y:clamp(zoneY*.55+(target?.y??ballPoint.y)*.45,.08,.92)};
 }
 return{x:p.baseX-d*.025,y:clamp(p.baseY+(ballPoint.y-.5)*.10,.08,.92)};
}
function resolveSpacing(players){for(let pass=0;pass<5;pass++)for(let i=0;i<players.length;i++)for(let j=i+1;j<players.length;j++){const a=players[i],b=players[j],dx=b.aiTarget.x-a.aiTarget.x,dy=b.aiTarget.y-a.aiTarget.y,d=Math.hypot(dx,dy);const required=(a.role==='DF'&&b.role==='DF')?.060:(a.role===b.role?.050:.044);if(d>0&&d<required){const push=(required-d)/2,nx=dx/d,ny=dy/d;a.aiTarget.x-=nx*push;a.aiTarget.y-=ny*push;b.aiTarget.x+=nx*push;b.aiTarget.y+=ny*push;}}players.forEach(p=>p.aiTarget=clampToRole(p,p.aiTarget.x,p.aiTarget.y));}
function passOptions(owner,team,opponents){return team.filter(p=>p!==owner).map(p=>{const prof=profile(owner),forward=(p.x-owner.x)*dir(owner.side),pressure=influenceAt(p,opponents),distance=dist(owner,p);const q1={x:owner.x+(p.x-owner.x)*.33,y:owner.y+(p.y-owner.y)*.33},q2={x:owner.x+(p.x-owner.x)*.66,y:owner.y+(p.y-owner.y)*.66};const lanePressure=(influenceAt(q1,opponents)+influenceAt(q2,opponents))*.5;const separation=Math.min(...opponents.map(o=>dist(o,p)),1);const risk=pressure*.42+lanePressure*.40+distance*.14-Math.min(.16,separation*.18);const reward=forward*.72+(p.role==='FW'?.17:p.role==='MF'?.11:.03)+Math.min(.14,separation*.16);return{player:p,risk,space:separation,score:reward-risk*(1-prof.risk*.42)+prof.vision/430+prof.decisions/700};}).sort((a,b)=>b.score-a.score);}
function pressureInfo(owner,opponents){const ordered=opponents.map(p=>({p,d:dist(owner,p)})).sort((a,b)=>a.d-b.d);const nearest=ordered[0]||null;const close=ordered.filter(x=>x.d<.11);const level=clamp((nearest?1-nearest.d/.13:0)+Math.max(0,close.length-1)*.24,0,1.45);return{nearest,close,level};}
function escapeTarget(owner,opponents){const info=pressureInfo(owner,opponents),d=dir(owner.side);let vx=d*.46,vy=(owner.baseY-owner.y)*.35;for(const item of info.close){const dx=owner.x-item.p.x,dy=owner.y-item.p.y,len=Math.hypot(dx,dy)||1;vx+=dx/len*(1.05-item.d*5);vy+=dy/len*(1.05-item.d*5);}const len=Math.hypot(vx,vy)||1,prof=profile(owner),stride=.055+prof.decisions/1900+prof.confidence*.025;return clampToRole(owner,owner.x+vx/len*stride,owner.y+vy/len*stride);}
function update({home,away,possession,ball,logicalOwner,momentum={home:.5,away:.5},phase='possession',teamBrain=null}){const teams={home,away},attack=possession||logicalOwner?.side||'home',defend=attack==='home'?'away':'home',attackers=teams[attack],defenders=teams[defend],ballPoint=predictedBall(ball),owner=logicalOwner||ball?.owner||nearest(attackers,ballPoint),attackBrain=teamBrain?.[attack]||null,defendBrain=teamBrain?.[defend]||null,pressers=selectPressers(defenders,ballPoint,phase,defendBrain),ownerPressure=owner?pressureInfo(owner,defenders):{level:0,close:[],nearest:null};for(const p of attackers){profile(p);let pt,intent=INTENTS.HOLD;if(p===owner){p.passOptions=passOptions(p,attackers,defenders).slice(0,5);if(ownerPressure.level>.52){const safe=p.passOptions.find(o=>o.risk<.62&&o.space>.045);pt=escapeTarget(p,defenders);intent=safe&&profile(p).vision+profile(p).decisions>150?INTENTS.QUICK_PASS:INTENTS.EVADE;}else{pt={x:ballPoint.x,y:ballPoint.y};intent=INTENTS.HOLD;}}else{pt=chooseSupportPoint(p,owner||ballPoint,attackers,defenders);if(p.role==='FW'&&(phase==='build_up'||phase==='final_third'||momentum[attack]>.58||attackBrain?.mode==='DESPERATION')){intent=INTENTS.RUN;pt.x+=dir(p.side)*(.03+profile(p).confidence*.035+(attackBrain?.risk||.5)*.025);}else intent=p.role==='DF'?INTENTS.OFFER:INTENTS.SUPPORT;}p.intent=intent;p.aiTarget=clampToRole(p,pt.x,pt.y);}for(const p of defenders){profile(p);const pt=defensiveTarget(p,ballPoint,attackers,pressers,defenders);p.intent=pressers.has(p)?INTENTS.PRESS:(p.role==='DF'?(nearest(attackers.filter(a=>a.role==='FW'),p)?INTENTS.MARK:INTENTS.COVER):INTENTS.LANE);p.aiTarget=clampToRole(p,pt.x,pt.y);}resolveSpacing(home);resolveSpacing(away);const nearestPresser=[...pressers].sort((a,b)=>dist(a,ballPoint)-dist(b,ballPoint))[0]||null;const ballPressure=nearestPresser?clamp(1-dist(nearestPresser,ballPoint)/Math.max(.04,(window.WLTeamBrain?.pressureThreshold(defendBrain)||.12)),0,1):0;return{attack,defend,owner,ballPoint,pressers,nearestPresser,ballPressure,ownerPressure,teamBrain,influence:{home:influenceAt(ballPoint,home),away:influenceAt(ballPoint,away)},passOptions:owner?.passOptions||[],escapeTarget:owner?escapeTarget(owner,defenders):null};}
function intentLabel(intent){return({[INTENTS.HOLD]:'контроль',[INTENTS.PRESS]:'прессинг',[INTENTS.COVER]:'страховка',[INTENTS.MARK]:'опека',[INTENTS.SUPPORT]:'поддержка',[INTENTS.RUN]:'рывок',[INTENTS.LANE]:'перекрытие',[INTENTS.RETURN]:'возврат',[INTENTS.OFFER]:'вариант паса',[INTENTS.TRACK]:'слежение',[INTENTS.EVADE]:'уход из-под прессинга',[INTENTS.QUICK_PASS]:'быстрый пас'})[intent]||'';}
window.WLTacticalAI={update,INTENTS,intentLabel,predictedBall,profile,influenceAt,passOptions,pressureInfo,escapeTarget};
})();
